# Generated by Django 4.1 on 2022-12-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTable',
            fields=[
                ('chapter', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chapter_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('metal', models.CharField(blank=True, max_length=50, null=True)),
                ('gems', models.CharField(blank=True, max_length=50, null=True)),
                ('mass', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, db_column='price ', null=True)),
                ('volume_product', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(blank=True, null=True)),
                ('minor_1', models.TextField(blank=True, null=True)),
                ('minor_2', models.TextField(blank=True, null=True)),
                ('minor_3', models.TextField(blank=True, null=True)),
                ('minor_4', models.TextField(blank=True, null=True)),
                ('minor_5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gallary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MethodDeliveryTable',
            fields=[
                ('method_delivery', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price_delivery', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'method_delivery_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_delivery', models.CharField(choices=[('post', 'почта'), ('company', 'транспортная компания'), ('person', 'курьер')], default='post', max_length=10)),
                ('price_order', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('surname', models.TextField(blank=True, null=True)),
                ('petronymic', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='main/img')),
            ],
            options={
                'db_table': 'gallary',
            },
        ),
    ]
