# Generated by Django 4.1.2 on 2022-10-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTable',
            fields=[
                ('chapter', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chapter_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('metal', models.CharField(blank=True, max_length=50, null=True)),
                ('gems', models.CharField(blank=True, max_length=50, null=True)),
                ('mass', models.TextField(blank=True, null=True)),
                ('price_field', models.IntegerField(blank=True, db_column='price ', null=True)),
                ('volume_product', models.IntegerField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(blank=True, db_column='id', null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gallary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MethodDeliveryTable',
            fields=[
                ('method_delivery', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price_delivery', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'method_delivery_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('price_order', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='main/img')),
            ],
            options={
                'db_table': 'gallary',
            },
        ),
    ]
